version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cicd-nodejs-app
hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
